name: Rust CI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo build
      run: cargo build --release
      working-directory: udp-redirect-rs
    - name: cargo test
      run: cargo test
      working-directory: udp-redirect-rs
